name: Test by Clang
on:
  push:

jobs:
  clang15:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: egor-tensin/setup-clang@v1.4
        with:
          version: 15
          platform: x64
      - run: sudo apt install -y libc++-15-dev lld-15
      - run: pip install meson ninja
      - run: CXX=clang++-15 CXX_LD=lld LDFLAGS=-L /usr/lib/llvm-15/lib meson setup build
      - run: meson test -C build -v
