name: Test by MSVC
on: [push, pull_request]

jobs:
  MSVC2019:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
      - run: pip install meson ninja
      - uses: ilammy/msvc-dev-cmd@v1.10.0
      - run: meson setup build
      - run: meson test -C build -v
  MSVC2022:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - run: pip install meson ninja
      - uses: ilammy/msvc-dev-cmd@v1.10.0
      - run: meson setup build
      - run: meson test -C build -v
